import type { Metadata } from "next";
import { Manrope, M_PLUS_1_Code } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", "cyrillic"],
});

const m_PLUS_1_Code = M_PLUS_1_Code({
    variable: "--font-M_PLUS_1_Code",
    subsets: ["latin", "vietnamese"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${m_PLUS_1_Code.variable} antialiased font-sans bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
